"""pipelines_stages_deals

Revision ID: db3b42464b7f
Revises: 0003_companies
Create Date: 2026-01-16 09:32:49.654372

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'db3b42464b7f'
down_revision: Union[str, None] = '0003_companies'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('pipeline_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pipeline_id')
    )
    op.create_index(op.f('ix_pipelines_tenant_id'), 'pipelines', ['tenant_id'], unique=False)
    op.create_table('stages',
    sa.Column('stage_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_won', sa.Boolean(), nullable=False),
    sa.Column('is_lost', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.pipeline_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stage_id')
    )
    op.create_index(op.f('ix_stages_pipeline_id'), 'stages', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_stages_tenant_id'), 'stages', ['tenant_id'], unique=False)
    op.create_table('deals',
    sa.Column('deal_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=True),
    sa.Column('contact_id', sa.String(length=64), nullable=True),
    sa.Column('pipeline_id', sa.String(length=64), nullable=False),
    sa.Column('stage_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.pipeline_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.stage_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_index(op.f('ix_deals_company_id'), 'deals', ['company_id'], unique=False)
    op.create_index(op.f('ix_deals_contact_id'), 'deals', ['contact_id'], unique=False)
    op.create_index(op.f('ix_deals_pipeline_id'), 'deals', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_deals_stage_id'), 'deals', ['stage_id'], unique=False)
    op.create_index(op.f('ix_deals_tenant_id'), 'deals', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deals_tenant_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_stage_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_pipeline_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_contact_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_company_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_stages_tenant_id'), table_name='stages')
    op.drop_index(op.f('ix_stages_pipeline_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_pipelines_tenant_id'), table_name='pipelines')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
